theme: jekyll-theme-minimal
title: Shalom Caruaru
description: [A Comunidade Católica Shalom surgiu com o objetivo de evangelizar. Presente em dezenas de países do mundo a Comunidade é formada por homens e mulheres que engajam-se em uma vida comunitária e missionária com a finalidade de levar o Evangelho de Jesus Cristo a todos os homens e mulheres. ]
logo: SHCaruaru.jpg
